### PR TITLE
feat: Configurable dark mode

### PR DESCRIPTION
**Pull request by fsbraun**
## Description

This PR makes the color scheme configurable on two levels: Project wide to either light, dark, or auto (i.e.,d defined by browser/OS). Users can switch their session to their preferred mode using a toggle in the toolbar.

Two new settings are introduced (as proposed by @jgadelange):

* **CMS_COLOR_SCHEME**: either `"light"`, `"dark"`, or `"auto"`. This defines the system wide setting. Default remains `"light"`.
* **CMS_COLOR_SCHEME_TOGGLE**: If set to `True` the toggle button will show in the toolbar for logged-in users to allow them to switch to their preferred mode. Defaults to `False`.

To avoid unexpected results with (not yet) dark-mode compatible packages or, even more important, custom plugins the standard settings will force django CMS into light mode (as proposed by @vinitkumar).

## Related resources

* Settings are automatically cascaded to the admin interface with https://github.com/django-cms/djangocms-admin-style/pull/460 (though not to the admin site)
* Overriding the OS setting (either by `CMS_COLOR_SCHEME` or the toggle button) is achieved by adding `data-color-scheme="light/dark"` to the document's `<html>` tag.
* Since rendering usually starts before the CMS javascript frontend is running, adding, e.g. `<html data-color-scheme="light">` to their base template is encouraged for sites fixing `CMS_COLOR_SCHEME` to `light`.
* The CMS javascript API has been extended by `CMS.API.Toolbar.set_color_scheme` and `CMS.API.Toolbar.get_color_scheme `.

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.
* [x] I have updated the documentation

### CODE REVIEW

**Comment by marksweb** [comment]
Love this 😁 

Screen Recording 2022-06-01 at 00 50 47

**Comment by vinitkumar** [comment]
@fsbraun Everything looks good. However, I see there are are changes done to two JS files (`cms.structureboard.js`, and `cms.toolbar.js`. Do they need to be built/compiled for this to work in live mode?

**Comment by fsbraun** [comment]
To work you'll have to run `gulp bundle`, `gulp icons`, and `gulp sass`.

**Review by vinitkumar — APPROVED** [review]
Looks good to me!

**Comment by marksweb** [comment]
@fsbraun it does indeed do those.

**Pull request merged**
