### PR TITLE
fixed readme quickstart section

### PR DESCRIPTION
**Pull request by greengoaxe**
### Incomplete command reported

On the [Readme file](https://github.com/django-cms/django-cms/blob/develop/README.rst), Quick start section, the current, and incomplete, command reported is :
> **(env) $ python manage.py**

The right command is:
> **(env) $ python manage.py runserver**

## Related resources

* #7008

## Checklist

* [x] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Review by TiredFingers — APPROVED** [review]
Checked it, it's usefull improvement. Don't see any reasons to denied

**Comment by marksweb** [comment]
👍 yep, valid change

**Review by marksweb — APPROVED** [review]

**Comment by vinitkumar** [comment]
@greengoaxe Merge develop into this branch for the builds to kick-in.

**Comment by crydotsnake** [comment]
Maybe we should think about using code blocks:
https://sublime-and-sphinx-guide.readthedocs.io/en/latest/code_blocks.html

Also on any other repositorys with example code :).

**Comment by crydotsnake** [comment]
Maybe we should think about using code blocks in the future: https://sublime-and-sphinx-guide.readthedocs.io/en/latest/code_blocks.html

Also in any other repository with example code :).

**Pull request merged**
