### PR TITLE
[feat] Added pre-migrate hook to check version 4 is intentional

### PR DESCRIPTION
**Pull request by marksweb**
## Description

This follows on from an idea started [here](https://github.com/django-cms/djangocms-versioning/pull/257#event-6126521892) as we move towards releasing django-cms v4 packages.

Added pre-migrate hook to check version 4 is intentional, via a setting.

If this setting isn't `True` then an exception is raised before migration occurs, thus ensuring not damage done to the database.

## Checklist

* [x] I have opened this pull request against ``develop-4``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by marksweb** [comment]
@Aiky30 Here's a potential implementation to confirm intentional installation of cms v4.

**Comment by Aiky30** [comment]
> @Aiky30 Here's a potential implementation to confirm intentional installation of cms v4.

@marksweb I'll base a PR into this PR that fixes the failures this week. :-) Thanks for adding this.

**Comment by marksweb** [comment]
Need a way to ignore the signal import. pyflakes doesn't listen to a `noqa` like flake8 does 🤦

**Review by Aiky30 — APPROVED** [review]
Looks good to me.

**Review by Aiky30 — APPROVED** [review]

**Pull request merged**
