### PR TITLE
Added fix to migrations to handle multi database routing

### PR DESCRIPTION
**Pull request by MichaelAnckaert**
### Summary

This pull request fixes an issue when using Django CMS with a multidatabase configuration. 

### Details

When using a multidatabase configuration the migrations needed a fix when overriding the Migration.apply method. This method should always check if a migration is allowed using the dbrouter. 

### Proposed changes in this pull request

The migrations cms.migrations.0019_set_pagenode and cms.migrations.0020_old_tree_cleanup have a custom apply method that is updated to check if migration is allowed using the dbrouter. 

### General checklist

* [X] I have updated the CHANGELOG.txt
* [X] I have created backports if necessary
* [X] I have updated the documentation and/or amended the upgrade section
      if necessary

### CODE REVIEW

**Comment by Aiky30** [comment]
@MichaelAnckaert I've found this fix when looking through old PR's. Are you able to create a changelog entry and update the branch?

It's similar to the following PR, the first brought up to date can come in: https://github.com/django-cms/django-cms/pull/6708/files

**Review by Aiky30 — DISMISSED** [review]
Please add a changelog entry and bring the branch back up to date.

**Comment by MichaelAnckaert** [comment]
@goutnet  @Aiky30 I've rebased the branch on the latest `develop` branch and added an entry to the  `CHANGELOG` file.

**Review by goutnet — APPROVED** [review]
LGTM

**Pull request merged**
