### PR TITLE
fix: update diff-dom and karma, run frontend tests on Chrome Headless

### PR DESCRIPTION
**Pull request by fsbraun**
## Description

This PR updates the karma JS testing environment to a current version. The PhantomJS headless browser is replaced by ChromeHeadless.

With this setup, `diff-dom` can be updated to 5.0.x, solving #7460 

## Related resources

* #7461 
* #7460
* #7583
* #7470 

## Checklist

* [x] I have opened this pull request against ``develop-4``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by vinitkumar** [comment]
You are in :godmode:. I tried doing this couple of time, failed and gave up!

**Review by vinitkumar — APPROVED** [review]

**Comment by vinitkumar** [comment]
@fsbraun Don't we also need this fix in CMS 3 as well? I think the issue was created against CMS 3?

**Review by marksweb — APPROVED** [review]
Fantastic 👏

**Comment by fsbraun** [comment]
@vinitkumar The big step ahead is webpack 5...

**Pull request merged**
