### PR TITLE
[Docs] Fixes incorrect default path for `CMSPluginBase.change_form_…

### PR DESCRIPTION
**Pull request by mbi**
## Description

The default template path for `CMSPluginBase.change_form_template` in the [documentation](https://docs.django-cms.org/en/latest/reference/plugins.html#cms.plugin_base.CMSPluginBase.change_form_template) is wrong.  

## Checklist

* [x] I have opened this pull request against ``develop``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventionnal commits guidelines](http://conventionnalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by NicolaiRidani** [comment]
Hi @mbi thx. If you want this PR to be reviewed (and speed up the process), please join our Slack (www.django-cms.org/slack) and ask someone from the PR Review team in #workgroup-pr-review to review it. That would help us a lot! Thx!

**Review by marksweb — APPROVED** [review]

**Review by crydotsnake — APPROVED** [review]

**Review by vinitkumar — APPROVED** [review]

**Comment by goutnet** [comment]
@vinitkumar should I cherry-pick this one onto the current release too? (since it is a doc-only patch)?

**Comment by marksweb** [comment]
@goutnet I would do. And whoever has RTD access still needs to add the 3.9 docs build. Still haven't tracked down who has access.

**Comment by NicolaiRidani** [comment]
> @goutnet I would do. And whoever has RTD access still needs to add the 3.9 docs build. Still haven't tracked down who has access (I think they should be able to fix #7031 also).

the #workgroup-documentation (which consists of @TiredFingers and me) has access - we'll check it tomorrow during our weekly meeting.

**Comment by marksweb** [comment]
Thanks @NicolaiRidani - in the versions on RTD (I think we've got RTD with a custom domain) you'll see the active builds, then under that you should be able to find the 3.9 release and activate it. Similar to this screenshot;

Screenshot 2021-06-02 at 20 47 59

**Pull request merged**
