### PR TITLE
prevents exception of page_attribute … as varname for invalid page_lo…

### LINKED ISSUE #5930: page_attribute "field-name" page_lookup as varname fails silently
### Summary

when using the templatetag 

```
{% page_attribute "field-name" page_lookup as varname %}
```

using a ``page_lookup`` of a CMS page which does not exist, this templatetag fails silently, without rendering any part of the template. This makes is very hard to track down the reason.

### Expected behaviour

just as
```
{% page_url page_lookup as varname %}
```
can be used on a CMS page which does not exist, hence setting ``varname`` to ``None``, one would expect the same behaviour for the templatetag ``page_attribute``.

#### Environment

* Python version: any
* Django version: 1.10
* django CMS version: 3.4.2, HEAD of releases/3.4.x

### PR DESCRIPTION
**Pull request by jrief**
### Summary

Fixes #5930

### Links to related discussion
https://github.com/divio/django-cms/issues/5930#issuecomment-457499815

### Proposed changes in this pull request
It adds the same behaviour to templatetag `{% page_attribute 'field_name' 'page_lookup' as varname %}` as is already implemented in templatetag `{% page_url 'page_lookup' as varname %}`

### Documentation checklist

* [x] I have updated CHANGELOG.txt if appropriate
* [ ] I have updated the release notes document if appropriate, with:
    * [ ] general notes
    * [ ] bug-fixes
    * [ ] improvements/new features
    * [ ] backwards-incompatible changes
    * [ ] required upgrade steps
    * [ ] names of contributors
* [ ] I have updated other documentation
* [x] I have added my name to the AUTHORS file
* [ ] This PR's documentation has been approved by Daniele Procida

### CODE REVIEW

**Comment by FinalAngel** [comment]
@jrief thank you very much. Would you be able to open the PR against develop?

**Comment by jrief** [comment]
Annotation: the failing unit test has nothing to do with this pull request, but is an artefact of other circumstances.

I also do not understand why we need an expert opinion on a feature which
* doesn't change anything, except adding
* a behaviour which is widely accepted for other templatetags

**Review by yakky — CHANGES_REQUESTED** [review]
@jrief implementing this behavior looks :100: to me

Maybe we need a test to ensure this behavior is preserved

Also: rebase against develop for merge

**Comment by jrief** [comment]
Closing and reopening against `releases/3.8`

**Pull request closed without merging**
