### PR TITLE
New feature: Dark mode for toolbar, page tree, structure tree, modals, login and wizard

### PR DESCRIPTION
**Pull request by fsbraun**
# Description

Since Django 3.2 the admin interface respects "dark mode", i.e. if selected by the user, the admin shows on dark background instead if light background. Dark mode is often used by IT people. Currently, django CMS does not respect a selected dark mode leading to a admin pages partly on dark background, partly on bright background giving the impression of a broken UI design.

This PR introduces changes to the css so than django CMS can respect dark mode. This affects the toolbar, page tree, structure tree and modals. It does not affect the admin site nor the frontend editing forms.

Changes:

* Replaced the $gray sass variables with css custom properties `--dca-gray` etc. (dca for django CMS association)
* Added different color codes for dark mode for those variables
* Replaced brighten and darken sass functions with css alternatives (mostly transform: `brightness()` since functions do not work on custom properties.
* Removed a few `!important` statements to allow other apps to properly adjust their admin forms to dark mode.
* Replaced a few left-over absolute black and white properties with $back  and $white to become flexible.
* Reflected @marksweb’s suggestion to have the django CMS color adjusted in dark mode to be better for the eye

## Related resources

* There is a similar PR for `djangocms-admin-style`. With both accepted django CMS will give a nice dark mode design: [PR 443](https://github.com/django-cms/djangocms-admin-style/pull/443)
* This is the second incarnation of #7238 without changes to the `static/css/3.9.0` files.

## Checklist

No tests are affected. 

* [x] I have opened this pull request against ``develop``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Review by vinitkumar — APPROVED** [review]
Looks good to me. Let's get this merged🚢  🚀

**Review by marksweb — APPROVED** [review]
Ok I'm happy with this.

Though I'm having trouble with `gulp sass` locally.

```
[21:10:10] Error (gulp-sass): cms/static/cms/sass/cms.wizard.scss
Error: $color: var(--dca-primary) is not a color.
   ╷
74 │             background: lighten($btn-action-bgcolor, 45%);
   │                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  cms/static/cms/sass/cms.wizard.scss 74:25  root stylesheet
```

**Comment by marksweb** [comment]
Sass building now 👍 

I'll merge this if you're happy with things @fsbraun

**Comment by vinitkumar** [comment]
@fsbraun What's the status of this one?

**Comment by fsbraun** [comment]
Should be merged! I just resolved the conflict in the `CHANGELOG.rst`. You can merge it.

**Pull request merged**
