### PR TITLE
FEATURE: Add Guide for Setting up the django CMS Documentation

### PR DESCRIPTION
**Pull request by crydotsnake**

### CODE REVIEW

**Comment by crydotsnake** [comment]
If you guys are wondering: why so many commits? 🤔 

I had to push my changes everytime. Because i couldnt setup my live preview in vscode for .rst files 😅

**Review by TiredFingers — APPROVED** [review]

**Comment by TiredFingers** [comment]
Here are some faild checks. As I see you need to include readme.rst to some toctree. But I thought that we have some article about docs here https://docs.django-cms.org/en/latest/contributing/documentation.html

**Comment by crydotsnake** [comment]
> But I thought that we have some article about docs here https://docs.django-cms.org/en/latest/contributing/documentation.html

Yes. But as i already mentioned in the Slack: I would recommend having documentation like that directly in the README.rst.

> Here are some faild checks. As I see you need to include readme.rst to some toctree. 

What do you mean?

**Comment by TiredFingers** [comment]
> Yes. But as i already mentioned in the Slack: I would recommend having documentation like that directly in the README.rst.

Sorry, I guess I missed it

> What do you mean?

It's not me, I read it in the failed tests. last time, when Nikolai and I merged pr with failed tests, we were told that it was not necessary.

**Comment by TiredFingers** [comment]
@crydotsnake Simon, I think I found problem. I was wrong and we don't need to include your file to any toctree. We need to exclude it from sphinx checks. I tried to update docs/conf.py with 

`exclude_patterns = ['build', 'env', 'README.rst']`

and it seems work

**Comment by crydotsnake** [comment]
Check seems okay now.

But i dont know, if this is the correct workflow here..

**Comment by crydotsnake** [comment]
What do you think @marksweb

**Comment by marksweb** [comment]
@crydotsnake Ok, so what's the purpose of this document when we've got this one already;

https://docs.django-cms.org/en/latest/contributing/documentation.html

Beyond that, I wouldn't call it "readme" because that's a little confusing. I'd call it something more related to its purpose & I'd probably not include it in the root of the docs.

**Review by TiredFingers — APPROVED** [review]
From my side everything is ok

**Comment by crydotsnake** [comment]
> @crydotsnake Ok, so what's the purpose of this document when we've got this one already;
> 
> https://docs.django-cms.org/en/latest/contributing/documentation.html
> 
> Beyond that, I wouldn't call it "readme" because that's a little confusing. I'd call it something more related to its purpose & I'd probably not include it in the root of the docs.

I dont want to include it in the docs. Only in the repository.

**Comment by TiredFingers** [comment]
@crydotsnake About banch of commits. We have politics about the way of creating pr. You need to squash your commits to 1. You can read more about it here https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

I don't think that this is the big problem, everybody was that guy who made a bunch of commits in one PR. You don't need to worry about it, just keep in mind

**Comment by crydotsnake** [comment]
> @crydotsnake About banch of commits. We have politics about the way of creating pr. You need to squash your commits to 1. You can read more about it here https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
> 
> I don't think that this is the big problem, everybody was that guy who made a bunch of commits in one PR. You don't need to worry about it, just keep in mind

Thanks for the reminder! :)

**Comment by marksweb** [comment]
> @crydotsnake About banch of commits. We have politics about the way of creating pr. You need to squash your commits to 1. You can read more about it here https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
> 
> I don't think that this is the big problem, everybody was that guy who made a bunch of commits in one PR. You don't need to worry about it, just keep in mind

The person who merges a PR should have the option to squash at the point of merge which then creates just the 1 commit.

**Comment by crydotsnake** [comment]
> > @crydotsnake About banch of commits. We have politics about the way of creating pr. You need to squash your commits to 1. You can read more about it here https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
> > I don't think that this is the big problem, everybody was that guy who made a bunch of commits in one PR. You don't need to worry about it, just keep in mind
> 
> The person who merges a PR should have the option to squash at the point of merge which then creates just the 1 commit.

That would be a great new GitHub feature mark!

**Comment by marksweb** [comment]
It already is a feature; https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request

**Comment by crydotsnake** [comment]
Okay yes. I saw it 😅

**Comment by TiredFingers** [comment]
> It already is a feature; https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request

Thanks, didn't know. Should we now change our pr policy?

**Pull request merged**
