### PR TITLE
adding django CMS release script (will be used starting 3.9.0 release)

### PR DESCRIPTION
**Pull request by goutnet**
## Description

This PR adds an script to automate the release process. This will be used for 3.9.0 and onward (will auto-merge this before starting the actual release cycle)

## Checklist

* [x ] I have opened this pull request against ``develop``
* [x] I have updated the **CHANGELOG.rst**
* [x] I have added or modified the tests when changing logic
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by goutnet** [comment]
@FinalAngel  @NicolaiRidani  for visibility (I'll merge this before starting 3.9 as this is the actual process used to create the release :) )

This file may change during the release cycle (debugging/improvement as I use it), but that's fine as it is standalone.

**Review by vinitkumar — APPROVED** [review]
Looks good to me. Let's get this merged and released 🚢  🚀

**Comment by goutnet** [comment]
Since I am waiting on Django 3.2 integration review/merge, I am also taking the time to polish/refine the script.

* separated some useful pieces for translation management
* narrowing the translation pull-in to clean the release
* likely play with `gh` (github cli client) to generate automatically the PR if I have enough time.

**Comment by goutnet** [comment]
=> done and merged

**Pull request merged**
