### PR TITLE
fix: Fixed RecursionError when extending templates

### PR DESCRIPTION
**Pull request by mihalikv**
## Description

When you have extends across multiple apps with same path CMS breaks with RecursionError.
Error trace:

```
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 323, in _get_placeholder_nodes_from_extend
    placeholders += _scan_placeholders(_get_nodelist(parent_template), node_class, None, block_names)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 200, in _scan_placeholders
    nodes += _get_placeholder_nodes_from_extend(node, node_class)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 322, in _get_placeholder_nodes_from_extend
    parent_template = _find_topmost_template(extend_node)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 333, in _find_topmost_template
    return _find_topmost_template(node, previous_context=previous_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/cms/utils/placeholder.py", line 335, in _find_topmost_template
    return extend_node.get_parent(get_context(extend_node))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/classytags/core.py", line 128, in __init__
    self.kwargs, self.blocks = self.options.parse(parser, tokens)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/classytags/core.py", line 104, in parse
    argument_parser = argument_parser_class(self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/classytags/parser.py", line 14, in __init__
    self.options = options.bootstrap()
                   ^^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/classytags/core.py", line 92, in bootstrap
    return StructuredOptions(
           ^^^^^^^^^^^^^^^^^^
  File "/home/vilo/django-cms/venv/lib/python3.11/site-packages/classytags/utils.py", line 39, in __init__
    self.breakpoints = copy(breakpoints)
                       ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/copy.py", line 76, in copy
    return copier(x)
           ^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
```
This PR fixes this issue. Django basically creates a history of already visited templates, to prevent recursion. For the purpose of "history", is used context which is passed to get_parent call. However, in CMS there is always created new context and Django is unable to create such a "history".
Code where Django creates history: https://github.com/django/django/blob/main/django/template/loader_tags.py#L105
## Related resources

https://github.com/django-cms/django-cms/issues/6563
https://github.com/django-cms/django-cms/pull/6564

## Checklist

* [X] I have opened this pull request against ``develop``
* [X] I have added or modified the tests when changing logic
* [X] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [X] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by fsbraun** [comment]
@mihalikv Can you give more details of your template extending setup? 
Since #6563 was fixed (or was it not?) by #6564, I try to understand where this recursion error comes from.

**Comment by mihalikv** [comment]
@fsbraun That previous fix, fixed it just for like one level of recursion not for infinite levels. I was not able to simulate it in the previous "recursion" test, but I was able to simulate it when another "nested_app" was added.

**Comment by fsbraun** [comment]
@mihalikv Could you have a look at the linting issues, please?

**Comment by mihalikv** [comment]
@fsbraun  Can you please run ruff action, if it's fixed ?

**Comment by mihalikv** [comment]
@fsbraun sorry for bothering I run ruff locally I hope it will be fine now. Can you run checks again ? Thanks

**Comment by mihalikv** [comment]
@fsbraun Sorry I was unaware that actions also run on a branch in my repo. It all passed except Publish python.

**Comment by mihalikv** [comment]
@fsbraun What do you think about that? Do you need something else from me? Thanks

**Review by fsbraun — COMMENTED** [review]
I've got just one little comment. (See below.) Sorry, I forgot to press "submit" and the comment was pending...

**Review by fsbraun — APPROVED** [review]

**Comment by fsbraun** [comment]
@mihalikv Do you think you can port that forward to django CMS 4 on the `develop-4` branch?

**Comment by mihalikv** [comment]
@fsbraun I broke that ruff again 😄  I will look into it 🤦🏻‍♂️

**Pull request merged**
