### PR TITLE
Merging 3.9.0 into develop

### PR DESCRIPTION
**Pull request by goutnet**
Merging 3.9.0 into develop

### CODE REVIEW

**Comment by goutnet** [comment]
by the look of it, a file "bundle.toolbar.min.js" should really be removed at some point but isn't, we'll have to fix this before merging, but waiting for the tests first.

@vinitkumar  thoughts?

**Review by marksweb — APPROVED** [review]

**Comment by goutnet** [comment]
since I got approval, I will perform the manual merge.

**Comment by goutnet** [comment]
Manually merged, waiting for tests to pass before closing this one.

**Comment by goutnet** [comment]
All test passed => closing (this has now been merged!)

**Pull request closed without merging**
