### PR TITLE
fix: some Django antipatterns

### PR DESCRIPTION
**Pull request by jrief**
## Description

**This PR does not change any functionality!**

It just fixes two anti-patterns in django-CMS:

`force_str(_("…some text…"))` is completely useless because it forces to stringify a proxy object. A better and faster way is to use `gettext("…some text…")` directly.

`HttpResponse(json.dumps(content), content_type="application/json")` probably is a legacy statement. Django introduced `JsonResponse` many versions ago.

## Related resources

We discussed about this during one of our biweekly meetings.

## Checklist

* [x] I have opened this pull request against ``develop-4``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

I ran all unit tests successfully on my local environment.

### CODE REVIEW

**Comment by jrief** [comment]
why am I considered as a new contributor and why this [notification](https://github.com/django-cms/django-cms/actions/runs/8612662588/job/23602344072?pr=7867) then fails?

**Comment by fsbraun** [comment]
@jrief I appreciate the initiative! IHMO in the admin files **all** `gettext_lazy` can be replaced by `gettext`, since all of them appear in a request response cycle. 

The only question I have: Why does pageadmin need to import `IntegrityError`?

**Comment by jrief** [comment]
> The only question I have: Why does pageadmin need to import `IntegrityError`?

ups...

some remaining from my private branch

**Review by marksweb — APPROVED** [review]

**Comment by marksweb** [comment]
Adding my approval to this as I'm passing, pending that bit of cleanup.

**Review by fsbraun — APPROVED** [review]

**Pull request merged**
