### PR TITLE
fix: remove fixed width for edit plugin popup (=> autowidth)

### PR DESCRIPTION
**Pull request by fabien-michel**
The edit plugin popup as a fixed width of 850px whereas the new plugin popup adapt width to the viewport.

This PR just make same popup width for edit popup

## Description

Remove fixed with of edit plugin popup

## Related resources

* #7336 

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Review by marksweb — CHANGES_REQUESTED** [review]
@fabien-michel Thank's for this.

Just a minor thing - could you revert the change to `cms/static/cms/js/dist/3.10.0/bundle.toolbar.min.js` please? Those `dist` files are generated as part of the release process, so the other changes you've made would then get added to those files as part of a future release.

**Review by marksweb — CHANGES_REQUESTED** [review]
@fabien-michel Thanks for that quick change.

Sorry, also forgot to mention this needs a line in the "unreleased" section of the `CHANGELOG.rst`. Could you put a short description in that section to explain what this change brings?

**Comment by fsbraun** [comment]
The failing backend tests are not due to the PR. But the failing frontend test is. @fabien-michel: I think it's the trailing commas the frontend is complaining about. Can you remove them? See GitHub Action's comments here: https://github.com/django-cms/django-cms/pull/7337/files. IMHO after these changes this is ready to merge!

**Review by marksweb — APPROVED** [review]

**Comment by fabien-michel** [comment]
Oh sorry didn't notice that. I've fixed the trailing commas.

**Comment by marksweb** [comment]
@fabien-michel Changes in develop need merging in to get the tests to pass. Then we can get this merged.

**Comment by fabien-michel** [comment]
Developer bounty: @NicolaiRidani

**Pull request merged**
