### PR TITLE
Fix doctest and updated relevant parts of docs config

### PR DESCRIPTION
**Pull request by marksweb**
## Description

`doctest` currently doesn't run. There's also some old links in the `intersphinx_mapping` and a `highlightlang` is deprecated.

## Related resources

* #7013

## Checklist

* [x] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Review by TiredFingers — APPROVED** [review]
Checked in my localhost in Windows 10x64 and it's works, all tests passed. Don't see any reasons to decline

**Review by TiredFingers — COMMENTED** [review]
phinx changelog about deprecated stuff

https://www.sphinx-doc.org/en/master/changes.html?highlight=highlightlang#id99

**Comment by greengoaxe** [comment]
@evildmp May you review and approve it?
Thanks
greengoaxe

**Review by Aiky30 — APPROVED** [review]

**Comment by evildmp** [comment]
LGTM, will merge once tests pass.

**Pull request merged**
