### PR TITLE
Fixed #6413: migrations 0019 and 0020 on multi db setups

### LINKED ISSUE #6413: migration dajngo cms 0019 does not apply successfully on multiple database
### Summary

migration dajngo cms 0019 apply on a database the does not belongs to cms.

### Expected behaviour

The migration is skipped

### Actual behaviour

When running `python manage.py migrate` the following error occurd

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/test.py", line 62, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python2.7/site-packages/django/test/runner.py", line 601, in run_tests
    old_config = self.setup_databases()
  File "/usr/local/lib/python2.7/site-packages/django/test/runner.py", line 546, in setup_databases
    self.parallel, **kwargs
  File "/usr/local/lib/python2.7/site-packages/django/test/utils.py", line 187, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 69, in create_test_db
    run_syncdb=True,
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/site-packages/cms/migrations/0019_set_pagenode.py", line 68, in apply
    connection.introspection.get_table_description(connection.cursor(), 'cms_page')
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/introspection.py", line 81, in get_table_description
    cursor.execute("SELECT * FROM %s LIMIT 1" % self.connection.ops.quote_name(table_name))
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "cms_page" does not exist
LINE 1: SELECT * FROM "cms_page" LIMIT 1
                      ^
```

### Environment

* Python version:
2.7
* Django version:
1.11.13
* django CMS version:
3.5.2

db router:
```
class XxxRouter(object):
    # (...)
    def allow_migrate(self, db, app_label, model_name=None, **hints):
        if db == 'xxx_db' or app_label == 'xxx':
            return db == 'xxx_db' and app_label == 'xxx'
        return None
```

Thanks for your help !

### PR DESCRIPTION
**Pull request by pglotov**
### Summary

Fixes [#6413](https://github.com/divio/django-cms/issues/6413)

### Documentation checklist

* [ ] I have updated CHANGELOG.txt if appropriate
* [ ] I have updated the release notes document if appropriate, with:
    * [ ] general notes
    * [ ] bug-fixes
    * [ ] improvements/new features
    * [ ] backwards-incompatible changes
    * [ ] required upgrade steps
    * [ ] names of contributors
* [ ] I have updated other documentation
* [ ] I have added my name to the AUTHORS file
* [ ] This PR's documentation has been approved by Daniele Procida

### CODE REVIEW

**Comment by FinalAngel** [comment]
@pglotov thank you for the contribution. Could you reopen the PR agains develop?

**Comment by pglotov** [comment]
done

**Comment by piotrekmonko** [comment]
@yakky any chance for a review?

**Comment by Aiky30** [comment]
@pglotov I've found this fix when looking through old PR's. Are you able to create a changelog entry and update the branch?

It's similar to the following PR, the first brought up to date can come in: https://github.com/django-cms/django-cms/pull/6721

**Review by Aiky30 — DISMISSED** [review]
Can you please bring the branch back up to date and add a changelog entry.

**Comment by pglotov** [comment]
done

**Comment by pglotov** [comment]
@Aiky30 please merge to develop branch

**Review by goutnet — APPROVED** [review]
LGTM

**Pull request merged**
