### PR TITLE
ci: Test python 3.13 and django 5.1

### PR DESCRIPTION
**Pull request by marksweb**
## Description

This adds to github tests, python 3.13 and django 5.1.

I've also removed testing against old django releases.

## Checklist

* [x] I have opened this pull request against ``develop-4``
* [ ] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined the channel #pr-reviews on our [Discord Server](https://discord-pr-review-channel.django-cms.org) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by marksweb** [comment]
Some of the test failures I've seen come from a case of `<h2>Page Permissions</h2> not in str` type error where I can see that there is heading of `<h2>permissions</h2>`. So I'm just wondering there if this is a django admin based test where the setup of django admin has changed or if this is an unrelated permissions section (it's painful to read the raw HTML output afterall so I may have missed/misunderstood something)

**Comment by fsbraun** [comment]
I've looked at the HTML. It seems that django has introduced some classes to the `<h2>` tag which make this test fail.

**Comment by vinitkumar** [comment]
@marksweb Let's resolve the merge conflicts and see if the new code fixes the test failures.

**Comment by vinitkumar** [comment]
@marksweb  I think the latest https://github.com/django-cms/django-cms/blob/develop-4/.github/workflows/test.yml already has this. Do we need this PR anymore?

**Comment by fsbraun** [comment]
Superseded by #8008

**Pull request closed without merging**
