### PR TITLE
Optimize populating title cache for Page model.

### PR DESCRIPTION
**Pull request by zkne**
## Description

Optimizes the way the title cache is populated.

## Related resources

* #7099 

## Checklist

* [ ] I have opened this pull request against ``develop``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by fsbraun** [comment]
@zkne Thanks very much for this PR! Can you have a look at the failing tests? Indeed, it would be great to have the improved population of the page content cache.

**Comment by zkne** [comment]
@fsbraun thanks for reminding me of this PR. I will update it in the following days.

**Comment by zkne** [comment]
@fsbraun Can you please check the PR now, I've updated the tests.

`test_editing_plugin_changes_page_modification_time_in_sitemap` wasn't written correctly as you can see with the new assert I've added.

**Review by fsbraun — APPROVED** [review]
I also tested this w/ versioning which monkey patches both `PageContent.objects` as well as `Page.page_content_set`. I do not see a side effect there.

**Review by marksweb — APPROVED** [review]

**Pull request merged**
