### PR TITLE
github actions for release/3.7

### PR DESCRIPTION
**Pull request by marksweb**
## Description

Shifting 3.7 support to github actions

## Checklist

* [ ] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by vinitkumar** [comment]
@marksweb What's blocking this PR? Let me know if I can help with something.

**Comment by marksweb** [comment]
@vinitkumar I think the casper tests were failing. I've not had chance to look at it for a few weeks.

Basically it's a case of debugging the results of the actions because I didn't expect the FE tests to fail.

**Comment by Aiky30** [comment]
@marksweb Is this PR still required?

**Comment by marksweb** [comment]
@Aiky30 I don't think so. I don't think we should be making any more 3.7 releases so I'll close.

**Pull request closed without merging**
