### PR TITLE
Page changed_date added to the Page tree admin actions dropdown template

### PR DESCRIPTION
**Pull request by kuvandjiev**
### Summary

Page changed_date added to the Page tree admin actions dropdown template

### Links to related discussion

N/A

### Proposed changes in this pull request

Just after the 'last change by' add 'last change on` in the Page actions dropdown menu.

last_change_on

### Documentation checklist

* [x] I have updated CHANGELOG.txt if appropriate
* [ ] I have updated the release notes document if appropriate, with:
    * [ ] general notes
    * [ ] bug-fixes
    * [ ] improvements/new features
    * [ ] backwards-incompatible changes
    * [ ] required upgrade steps
    * [ ] names of contributors
* [ ] I have updated other documentation
* [ ] I have added my name to the AUTHORS file
* [ ] This PR's documentation has been approved by Daniele Procida

### CODE REVIEW

**Comment by FinalAngel** [comment]
@kuvandjiev thank you very much for the addition, could you rebase your effort to develop to get the tests to pass? :)

**Comment by kuvandjiev** [comment]
> @kuvandjiev thank you very much for the addition, could you rebase your effort to develop to get the tests to pass? :)

Hello @FinalAngel ,

Thank you for spending time for my PR. I have rebased my branch to latest develop but the tests are still failing (not related to changes I have made).

**Comment by FinalAngel** [comment]
@kuvandjiev passing now, thank you for rebasing. Tests still seem shaky at some times.

**Comment by goutnet** [comment]
@kuvandjiev sorry for the late ping, can you help rebase it again, I would want to have this in the coming release as it had been accepted. 

Thanks and sorry for the request again.

**Comment by goutnet** [comment]
so … this is the last in the 3.9.0 bucket.

can somebody help me rebasing/fixing the conflict so I can merge?

**Comment by goutnet** [comment]
@here 3.9.0RC release cycle will start in a few hours, I would love to merge this one, but I have 2 choices here:
* rebase manually on my fork to run the tests, then merge (that may also cause the original author to be lost from gh point of view).
* leave this one for next release …

@kuvandjiev can you help?

**Comment by goutnet** [comment]
I re-opened the same PR under #7046 to fix the conflict

**Comment by goutnet** [comment]
@kuvandjiev since I rebased your code in a different PR, I am going to close this one, and manually credit you in the changelog.

**Comment by kuvandjiev** [comment]
Apologies, I have completely missed that thread. Thank you for sorting it out.

**Comment by goutnet** [comment]
no problem, your PR is merged in 3.9.0rc1 :)

**Pull request closed without merging**
