### PR TITLE
Issue 4646 refactor details view

### PR DESCRIPTION
**Pull request by philippze**
Hi!

I've finally done the refactoring I promised more than a year ago in issue #4646.

The file `cms/views.py` is now looking *very* different, but I've taken care that I don't change any logic, and that all test still pass after every commit (using Django 1.10).

I've left a few TODO-comments where I didn't understand the code or would suggest a further change that might concern the logic.

Have fun with reviewing the diff...

Best
Philipp

### CODE REVIEW

**Comment by czpython** [comment]
Hello @philippze,
Thanks for the contribution.
Given the nature of this change, we're planning to release it with the 3.5.0 release.
I'm planning to review this thoroughly at PyCon (2 weeks from now).

**Comment by czpython** [comment]
Small update.. I have started the review, but this is going to take some time.

**Comment by philippze** [comment]
Great! Don't hesitate to ask if you find something strange. I should still roughly remember what I did...

**Comment by philippze** [comment]
Hi @czpython , it seems the change was too big :)

However, I like the Django CMS and think that improving the code quality is important, and would like to contribute to that.

You would probably prefer to merge little changes, right? Then, we could close this pull request, and instead begin with something little.

**Comment by FinalAngel** [comment]
@czpython what you think of these days? Can this be merged?

**Comment by Aiky30** [comment]
This needs an extensive review and testing before it can be accepted and released.

**Comment by goutnet** [comment]
@philippze It would likely be easier for us to have those kind of modifications coming in smaller variation.

Could you break this is smaller patches for us to review&merge?

If you're fine with this, I'll close this one here and wait for your next PR

**Comment by goutnet** [comment]
Well it definitely is, here are some evidences:

* @NicolaiRidani  is doing a great job into steering a new association driving the project forward
* working on next release 3.8.1 (hopefully in the next 2~3 weeks)
* 4.x is also progressing

So… definitely alive :)

**Comment by goutnet** [comment]
@philippze  since the coming release will likely be the last feature release on 3.x, and the merging window is closing this saturday, I am not sure if this would be a helpful merge addition to 3.x.

After this release, the focus will go on the 4.x serie. So if you want to help us, working on the 4.x code cleaning would be more useful :)

**Comment by vinitkumar** [comment]
@marksweb @fsbraun Should we just close this one. It's almost half a decode old now.

**Comment by vinitkumar** [comment]
@fsbraun @marksweb Let's just close this PR. No need to keep it hanging anymore.

**Pull request closed without merging**
