### PR TITLE
Fixed browser freezing on cms toolbar markup refresh after plugin edit

### PR DESCRIPTION
**Pull request by nichoski**
## Related resources
This fixes the bug reported here:
https://github.com/django-cms/django-cms/issues/7069

To update the contents of the django-cms toolbar after a plugin update, instead of creating a diff between old content and new content and applying the diff, this fix simply replaces the old content with the new content. This is because on sites with more content, the diff creating process is incredibly slow. Please see issue 7069 for more info.

* [x] I have opened this pull request against ``develop``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by vinitkumar** [comment]
@nichoski The code looks good. If possible, can you please post a GIF or video of this fixing the slowness of diff creation comparing it to old code? That would be really nice to be documented here. Thanks.

**Comment by vinitkumar** [comment]
@nichoski There is a failing test. Please make sure that the tests are passing.

**Comment by nichoski** [comment]
Yes @vinitkumar I saw it. I'll fix it soon.

**Comment by nichoski** [comment]
@vinitkumar the test is fixed. Please review when you can.

**Review by vinitkumar — APPROVED** [review]
Looks good to me. Let's get this merged and released 🚢  🚀

**Review by marksweb — APPROVED** [review]

**Pull request merged**
