### PR TITLE
Fix typos in the docs using codespell

### PR DESCRIPTION
**Pull request by cclauss**
## Description
Fix typos in the docs using https://pypi.org/project/codespell
```
codespell -w *.rst
codespell -w docs
```

## Related resources

* #...
* #...

## Checklist

* [x] I have opened this pull request against ``develop``
* [ ] I have added or modified the tests when changing logic
* [ ] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Review by marksweb — APPROVED** [review]
This seems like a neat tool @cclauss 👌

Do you know if it can integrate with pre-commit hooks or github actions?

**Comment by crydotsnake** [comment]
> Do you know if it can integrate with pre-commit hooks or github actions?

I believe it can be!: https://github.com/pypa/pip/issues/7689

**Comment by cclauss** [comment]
I put it GitHub Actions in this PR but it can also be put into pre-commit.

**Comment by marksweb** [comment]
@cclauss thanks again. I'll merge this as it's a good step forward - but I do like the sound of pre-commit handling this also.

**Pull request merged**
