### PR TITLE
Fix: Toolbar bug in 3.10rc1

### PR DESCRIPTION
**Pull request by marksweb**
Includes toolbar bugfix for issue in 3.10rc1

### CODE REVIEW

**Comment by goutnet** [comment]
Hi Mark can you resolve the conflicts? seems you modify the 3.9.x files in there, we would need to remove the generated files from the PR.

**Comment by marksweb** [comment]
@goutnet ah yes. Maybe I got a bit carried away thay the toolbar was working.

I'll resolve when I get chance 👍

**Comment by vinitkumar** [comment]
@marksweb Actually, these build files need not be committed with this, @goutnet should be generating new ones for the 3.10.0rc2 release. He just needs to merge the rest of the code.

**Comment by goutnet** [comment]
well they need to be modified on 3.9, but need regenerating on 3.10.

can't merge 3.9files in 3.10
-- 

Florian Delizy

**Comment by vinitkumar** [comment]
@marksweb merged your other PR. Please make a fresh PR for this

**Pull request closed without merging**
