### PR TITLE
Django 3.2 use HttpResponse.headers in place of ._headers

### PR DESCRIPTION
**Pull request by pcolmant**
## Description

As in the release notes of Django 3.2 (https://docs.djangoproject.com/en/3.2/releases/3.2/#requests-and-responses) using repsonse.headers in place of response._headers resolve

## Related resources

* Django 3.2 release notes: https://docs.djangoproject.com/en/3.2/releases/3.2/

## Checklist

* [x] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [x] I have added or modified the tests when changing logic
* [ ] I have read the [contribution guidelines ](https://github.com/django-cms/django-cms/blob/develop/CONTRIBUTING.rst) and I have joined #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by pcolmant** [comment]
@vinitkumar Can you review this PR ? Or take inspiration of it for the 3.2 tests of #7018 . Kr.

**Comment by vinitkumar** [comment]
> @vinitkumar Can you review this PR ? Or take inspiration of it for the 3.2 tests of #7018 . Kr.

This is awesome work @pcolmant. Let  me see if I can cherry pick your changes in my own PR.

**Comment by vinitkumar** [comment]
@pcolmant Are you on the slack channel for the django-cms  or can we talk somewhere. I don't think cherry-picking some of your changes in possible, because they seem to be mixed up doing different things. I wanted to basically cherry pick the fix for compile messages.

**Comment by vinitkumar** [comment]
@pcolmant Alright, I can co-commit this with you as co-author. I would have just merged your commits but  don't want to deal with the merge conflicts and at the same time, you should get credit for the work you did.

**Comment by vinitkumar** [comment]
@pcolmant Why don't you push the commits to my branch directly? Since my PR is already in progress, it will get merged. Else, we will have two completing PRs and duplication of work at the same time.

**Comment by vinitkumar** [comment]
Hey @pcolmant, I have cherry-picked the last two commits and they merged without any conflicts. Thanks for your contribution. If you do any more changes on your branch, I will cherry-pick them.

**Comment by goutnet** [comment]
It sounds like we can safely close this one, right?

@vinitkumar  ?

**Comment by vinitkumar** [comment]
#7018 is merged already, hence closing this PR.

**Pull request closed without merging**
