### PR TITLE
Cache not invalidated when using a PlaceholderField outside the CMS #6912

### PR DESCRIPTION
**Pull request by pierreben**
## Description

Since v3.6.0, when using a PlaceholderField outside the CMS, the cache is not invalidated when updating the placeholder content.
On [this commit](https://github.com/divio/django-cms/commit/99880979884de94b1f2784bb830ad5cf6d7bdea7#diff-5c9765ac0e61c2e87b3cea96392a6df2L1117), the value of the clear_cache attribute changed from True to False, and the [clear_cache method is never called in this case](https://github.com/divio/django-cms/blob/release/3.7.x/cms/models/placeholdermodel.py#L499).

I've created a new pull request as the previous was invalid and added tests.

## Related resources

* https://github.com/divio/django-cms/commit/99880979884de94b1f2784bb830ad5cf6d7bdea7#diff-5c9765ac0e61c2e87b3cea96392a6df2L1117
* https://github.com/divio/django-cms/blob/release/3.7.x/cms/models/placeholdermodel.py#L499
* https://github.com/nephila/djangocms-blog/issues/484

## Steps to reproduce

1. Create a custom model containing a PlaceholderField

```
class MyModel(models.Model):
    body_placeholder = PlaceholderField("Body")
```

2. Activate CACHE on the CMS

```
CMS_CACHE_DURATIONS = {
    "menus": 3600,
    "content": 3600,
    "permissions": 3600
}
```

3. Create a MyModel instance, a view and template to display it 

4. Edit the my_model_object placeholder field content within a template using the render_placeholder template tag:

`{% render_placeholder my_model_object.body_placeholder %}`

5. Open the MyModel instance view in a private session to compare the content.

6. Repeat steps 4 and 5 twice if the content doesn't differs.

## Expected behaviour

The contents are always the same between the two browser sessions.

## Actual behaviour

The contents differs as the cache is not invalidated when updating the body_placeholder content.

## Suggested correction

In the [mark_as_dirty method](https://github.com/divio/django-cms/blob/release/3.7.x/cms/models/placeholdermodel.py#L489), force clear_cache when the attached model is not a Page or a StaticPlaceholder. 

## Checklist

* [x] I have opened this pull request against ``develop``
* [x] I have updated the **CHANGELOG.rst**
* [x] I have added or modified the tests when changing logic

### CODE REVIEW

**Comment by pierreben** [comment]
Any news on this issue ? 

It affects all our projects using [djangocms-blog](https://github.com/nephila/djangocms-blog)  :(

**Review by Aiky30 — DISMISSED** [review]
@pierreben My apologies that it has taken this long to review your change. This looks good and I'm grateful that you have also provided a test. 

Can you please add a changelog entry into the changelog, this ensures that we mention your fix in any official releases. 

Once this has a changelog entry int he unreleased section of the changelog I will approve this change, once approved we can start to look at getting it merged and released. 

Again thank you for your effort regarding this fix.

**Comment by pierreben** [comment]
@Aiky30 , thank you for the fix analysis.

I've updated the changelog ;)

**Comment by palmitoto** [comment]
Why this MR is not yet merged ? Django-cms is not working without that patch.

A solution is provided since December 2020, it's too long to patch a critical issue like that.

**Comment by NicolaiRidani** [comment]
> Why this MR is not yet merged ? Django-cms is not working without that patch.
> 
> A solution is provided since December 2020, it's too long to patch a critical issue like that.

Hi @palmitoto I can understand your annoyance about the delay. Unfortunately, we are not in a good position at the moment in terms of resources, plus there is a problem with Travis that we are working on solving. But rest assured that we will try to resolve this quickly. 

With the founding of the[ django CMS Association](https://www.django-cms.org/en/blog/2020/08/04/the-importance-of-the-django-cms-association/), we have started an initiative that aims to foster contribution. Among many other community groups, we also have a work group for reviewing pull requests and a work group that takes care of release management. Both teams are happy to receive any support. We invite everyone to join us! 

If you want to learn more, feel free to contact me, otherwise more information can be found [here](https://github.com/django-cms/django-cms-mgmt/blob/master/community%20tasks/list%20of%20all%20community%20tasks.md 
): 

You are also welcome to join our Slack channel: www.django-cms.org/slack to get in touch with the team. 

Best
Nicolai

**Review by marksweb — APPROVED** [review]

**Comment by greengoaxe** [comment]
Hi @Aiky30,
may you review and approved it?
Thanks,
greengoaxe

**Comment by goutnet** [comment]
@Aiky30 since we are trying to make the Changelog happen more automatically, and based on your comments, I am updating the branch and schedule this one for merge.

**Comment by goutnet** [comment]
merged! and right in time for 3.9.0!

**Pull request merged**
