### PR TITLE
Improved performance of 'cms list plugins'.

### PR DESCRIPTION
**Pull request by vytisb**
### Summary

Avoid calculating `plugin_report()` twice.

### General checklist

* [X] I have updated the CHANGELOG.txt
* [ ] I have created backports if necessary
* [ ] I have updated the documentation and/or amended the upgrade section
      if necessary

### CODE REVIEW

**Comment by Aiky30** [comment]
@vytisb  I've found this fix when looking through old PR's. Are you able to create a changelog entry and update the branch?

**Review by Aiky30 — CHANGES_REQUESTED** [review]
Please bring the branch back up to date and add a changelog entry.

**Comment by vytisb** [comment]
Rebased and added a changelog entry.

**Comment by goutnet** [comment]
@NicolaiRidani  this one seems mergeable? can we rebase first though?

**Review by vinitkumar — APPROVED** [review]

**Pull request merged**
