### PR TITLE
Update menu_pool.py

### PR DESCRIPTION
**Pull request by WrapTheCode**
This forks solves the problem with bad translation of menu.
https://github.com/django-cms/django-cms/issues/6989

## Description

If we disable language prefix for default language - **get_language_from_request(request, check_path=True)** returns **None**
So language code is taken from a cookie saved by previosly selected language and menu shows in a wrong translation.

## Related resources

https://github.com/django-cms/django-cms/issues/6989

### CODE REVIEW

**Comment by vinitkumar** [comment]
@WrapTheCode Please merge develop into this branch for build to kick in.

**Comment by marksweb** [comment]
Hi @WrapTheCode. I've updated your branch with develop to get the latest test results and there's 2 failures.

Here's the details from one of the test runs;

```
FAIL: test_cms_menu_public_with_multiple_languages (cms.tests.test_menu.FixturesMenuTests)
Publishing public drafts....
----------------------------------------------------------------------
1.	*  home [1]
Traceback (most recent call last):
2.	*  página 1 [3]
  File "/home/runner/work/django-cms/django-cms/cms/tests/test_menu.py", line 419, in test_cms_menu_public_with_multiple_languages
3.	*  página 2 [5]
    [page.get_absolute_url('en', fallback=False) for page in pages],

AssertionError: Sequences differ: ['/de/', '/de/p2/', '/de/p2/p3/', '/de/p4/',[48 chars]p8/'] != ['/en/', '/en/p2/', '/en/p2/p3/', '/en/p4/',[48 chars]p8/']
========================================


First differing element 0:
Total:     3
'/de/'
Published: 3
'/en/'

- ['/de/',
?    -

+ ['/en/',
?     +

-  '/de/p2/',
?    -

+  '/en/p2/',
?     +

-  '/de/p2/p3/',
?    -

+  '/en/p2/p3/',
?     +

-  '/de/p4/',
?    -

+  '/en/p4/',
?     +

-  '/de/p4/p5/',
?    -

+  '/en/p4/p5/',
?     +

-  '/de/p6/',
?    -

+  '/en/p6/',
?     +

-  '/de/p6/p7/',
?    -

+  '/en/p6/p7/',
?     +

-  '/de/p6/p8/']
?    -

+  '/en/p6/p8/']
?     +


======================================================================
FAIL: test_hide_untranslated (cms.tests.test_multilingual.MultilingualTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/django-cms/django-cms/cms/tests/test_multilingual.py", line 179, in test_hide_untranslated
    self.assertNotEqual(list_1, list_2)
AssertionError: [2, 4] == [2, 4]

----------------------------------------------------------------------
Ran 1124 tests in 190.595s

FAILED (failures=2, skipped=2)
```

Could you please take a look at this against your changes to establish what's happened?

**Comment by vinitkumar** [comment]
@WrapTheCode please fix the test failures in this branch.

**Comment by goutnet** [comment]
@WrapTheCode can you help checking the test failed?

**Comment by fsbraun** [comment]
Solved by #7517 for v4: It displays the default language if language prefix are disabled for it.

**Pull request closed without merging**
